

CREATE TABLE `geno` (
  `chr` enum('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19') NOT NULL,
  `pos` INT UNSIGNED NOT NULL,
  `ref` enum('A', 'T', 'G', 'C') NOT NULL,
  `alt` enum('A', 'T', 'G', 'C') NOT NULL,
  `rsid` VARCHAR(16) DEFAULT NULL,
  `most_severe_consequence` enum('intergenic_variant','upstream_gene_variant','non_coding_transcript_exon_variant','non_coding_transcript_variant','downstream_gene_variant','intron_variant','synonymous_variant','missense_variant','5_prime_UTR_variant','splice_region_variant','3_prime_UTR_variant','NMD_transcript_variant','stop_retained_variant','stop_gained','splice_acceptor_variant','splice_donor_variant','start_lost','mature_miRNA_variant','stop_lost','coding_sequence_variant','incomplete_terminal_codon_variant') NOT NULL,
  `consequences` set('intergenic_variant','upstream_gene_variant','non_coding_transcript_exon_variant','non_coding_transcript_variant','downstream_gene_variant','intron_variant','synonymous_variant','missense_variant','5_prime_UTR_variant','splice_region_variant','3_prime_UTR_variant','NMD_transcript_variant','stop_retained_variant','stop_gained','splice_acceptor_variant','splice_donor_variant','start_lost','mature_miRNA_variant','stop_lost','coding_sequence_variant','incomplete_terminal_codon_variant') NOT NULL,
  `n_genotypes` TINYINT UNSIGNED NOT NULL,
  `C57BL_6J` TINYINT(1) UNSIGNED DEFAULT NULL,
  `129P2_OlaHsd` TINYINT(1) UNSIGNED DEFAULT NULL,
  `129S1_SvImJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `129S5SvEvBrd` TINYINT(1) UNSIGNED DEFAULT NULL,
  `AKR_J` TINYINT(1) UNSIGNED DEFAULT NULL,
  `A_J` TINYINT(1) UNSIGNED DEFAULT NULL,
  `BALB_cJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `BTBR` TINYINT(1) UNSIGNED DEFAULT NULL,
  `BUB_BnJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `C3H_HeH` TINYINT(1) UNSIGNED DEFAULT NULL,
  `C3H_HeJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `C57BL_10J` TINYINT(1) UNSIGNED DEFAULT NULL,
  `C57BL_6NJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `C57BR_cdJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `C57L_J` TINYINT(1) UNSIGNED DEFAULT NULL,
  `C58_J` TINYINT(1) UNSIGNED DEFAULT NULL,
  `CAST_EiJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `CBA_J` TINYINT(1) UNSIGNED DEFAULT NULL,
  `DBA_1J` TINYINT(1) UNSIGNED DEFAULT NULL,
  `DBA_2J` TINYINT(1) UNSIGNED DEFAULT NULL,
  `FVB_NJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `I_LnJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `KK_HiJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `LEWES_EiJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `LP_J` TINYINT(1) UNSIGNED DEFAULT NULL,
  `MOLF_EiJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `NOD_ShiLtJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `NZB_B1NJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `NZO_HlLtJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `NZW_LacJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `PWK_PhJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `RF_J` TINYINT(1) UNSIGNED DEFAULT NULL,
  `SEA_GnJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `SPRET_EiJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `ST_bJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `WSB_EiJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  `ZALENDE_EiJ` TINYINT(1) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`chr`, `pos`, `ref`, `alt`),
  KEY (`chr`, `pos`, `consequences`),
  KEY (`most_severe_consequence`),
  KEY (`rsid`),
  KEY (`n_genotypes`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

